# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userId',
            new_name='location',
        ),
        migrations.AddField(
            model_name='accomodations',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='postal',
            field=models.CharField(blank=True, default=b'', max_length=100, unique=True),
        ),
    ]
