# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0002_auto_20180112_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodations',
            name='idAdvertisement',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
