# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0003_accomodations_idadvertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodations',
            name='idAdvertisement',
        ),
    ]
