# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0004_remove_accomodations_idadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodations',
            name='rules',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
