# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0005_accomodations_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodations',
            name='address',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='accomodations',
            name='image2',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomodations',
            name='image3',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomodations',
            name='image4',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attractions',
            name='address',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
