# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0006_auto_20180113_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodations',
            name='locationMap',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
