# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0007_accomodations_locationmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodations',
            name='locationMap',
            field=models.TextField(),
        ),
    ]
