# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0008_auto_20180113_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='locationMap',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='locationMap',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
