# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0009_auto_20180113_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='description1',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description2',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='attractions',
            name='description3',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='attractions',
            name='title1',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='attractions',
            name='title2',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='attractions',
            name='title3',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='accomodations',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='accomodations',
            name='extraInfo',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='accomodations',
            name='locationMap',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='accomodations',
            name='rules',
            field=models.TextField(default=b''),
        ),
    ]
