# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0011_auto_20180114_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(),
        ),
    ]
