# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0014_restaurant_pricerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='built',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='attractions',
            name='kindOfAttractions',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
