# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 11:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_house_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_creation',
            name='image',
        ),
        migrations.AlterField(
            model_name='house_creation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
